function Promeni(a)
{
    document.getElementById("prvi").src=a.src;
    var b=a.src.lastIndexOf("/")+1;
    var c=a.src.lastIndexOf(".");
    var pos=a.src.substring(b,c);
	d=pos;
	if(d=='slika8')document.getElementById("p1").innerHTML = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla tristique rutrum nibh quis placerat. Nunc eget enim quis dolor feugiat dictum. Donec egestas sit amet velit varius mollis. Pellentesque non mauris nunc. Donec iaculis posuere dolor, eget scelerisque arcu placerat id. Cras faucibus eu neque sed rhoncus. Donec aliquet posuere vestibulum. Duis tristique velit venenatis massa pretium gravida. Sed in malesuada leo, sit amet convallis quam. Maecenas tortor justo, tempor non libero a, mollis tristique est.";
	if(d=='slika9')document.getElementById("p1").innerHTML = "Nunc congue volutpat tellus, id posuere diam auctor eu. Suspendisse imperdiet imperdiet ante, id ultrices justo ultricies id. Phasellus leo ex, pellentesque vel purus id, fermentum mollis mauris. Vivamus id pretium nunc. Sed nec mi ac ipsum suscipit consequat. Vestibulum in ligula accumsan, pretium sapien at, tincidunt velit. In interdum elementum nulla at tincidunt. Sed tristique mauris faucibus mauris fermentum tincidunt.";
	if(d=='slika10')document.getElementById("p1").innerHTML = "Donec vestibulum elit arcu, sed aliquet ante imperdiet quis. Etiam posuere quam sed sapien gravida venenatis. Proin nec mauris diam. Etiam auctor mattis risus, quis malesuada enim sagittis vel. Nullam eget mauris eu lacus sollicitudin consequat et ut quam. Ut mollis varius nisl nec malesuada. Suspendisse eros urna, finibus in tellus sed, hendrerit efficitur diam. Vestibulum ac venenatis velit. Donec vestibulum dictum nisi. Donec tellus leo, viverra in efficitur nec, finibus et dolor. Cras diam sapien, eleifend eget elit eu, ultricies maximus ante. Nullam sed tristique ligula. Aenean sapien justo, ultricies et quam et, semper imperdiet lacus. Phasellus posuere, neque eget placerat posuere, felis sem sollicitudin lacus, vel efficitur metus ex quis nibh.";
	if(d=='slika1')document.getElementById("p1").innerHTML = "Morbi tincidunt nisl eget est volutpat finibus. Donec posuere posuere vulputate. Aliquam mollis odio non purus fermentum, sit amet pharetra ante feugiat. Aliquam ut nibh pellentesque dolor iaculis ornare. Praesent tincidunt euismod tortor id luctus. Maecenas nec tincidunt tellus. Vestibulum auctor ornare diam, a eleifend magna tincidunt eget. Morbi fringilla libero diam, at accumsan massa mollis sed. Mauris nibh justo, pellentesque ac pulvinar ut, bibendum sed tortor. Nam dui arcu, interdum in urna sit amet, venenatis imperdiet ante. Suspendisse non libero metus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque vulputate nulla sit amet aliquet volutpat. Donec sagittis risus neque, vitae sodales ex dictum at.";
	if(d=='slika2')document.getElementById("p1").innerHTML = "Quisque pulvinar diam massa, ut mollis mi malesuada non. Suspendisse a posuere est. Nulla facilisi. Aliquam turpis elit, fringilla in varius volutpat, vulputate a ante. Pellentesque laoreet, nisi in ullamcorper sagittis, justo elit maximus nisl, quis tincidunt metus odio vitae massa. Sed tristique lorem sit amet mattis varius. Nam enim orci, scelerisque ac maximus suscipit, mattis ac justo. Pellentesque ut tempus nisl. Proin sit amet nibh sit amet nisl fringilla tincidunt. Nullam felis dolor, placerat id diam at, varius accumsan risus. Quisque volutpat fringilla libero, eget efficitur justo rhoncus eu.";
	if(d=='slika3')document.getElementById("p1").innerHTML = "Praesent et tortor nec mauris maximus vehicula. Ut ex urna, ullamcorper id quam quis, imperdiet suscipit purus. Nulla enim sapien, viverra eu augue a, egestas laoreet elit. Phasellus sagittis est egestas bibendum suscipit. Nunc vitae dictum orci. Integer malesuada ornare purus, ut venenatis lorem luctus elementum. Vestibulum tincidunt viverra dignissim. Sed non ultricies ipsum, id convallis purus.";
	if(d=='slika5')document.getElementById("p1").innerHTML = "Integer consequat tortor eu mi fringilla cursus. Vivamus urna risus, placerat vitae nibh eu, blandit vulputate massa. Aenean faucibus consequat elit et placerat. Donec consequat mattis orci, nec mollis massa fermentum id. Maecenas sed risus varius, malesuada nibh at, dignissim justo. Aliquam ac lorem vitae nisl hendrerit elementum. Integer maximus consequat magna eu ornare. Vivamus fermentum nisi vel varius ultrices. Integer gravida laoreet mollis. Proin risus arcu, rhoncus eu leo ultrices, iaculis facilisis quam. Proin elementum nisl ac nisl fermentum, sit amet porttitor nulla bibendum. Duis aliquam velit risus, quis auctor justo molestie ut. Phasellus lectus augue, feugiat ac felis eu, scelerisque lacinia neque. Aliquam non ultrices orci.";
	if(d=='slika6')document.getElementById("p1").innerHTML = "In et pharetra ipsum, quis vulputate tortor. Ut nec commodo velit, ac feugiat risus. Mauris non condimentum lacus. Suspendisse diam purus, tristique eget malesuada a, dapibus ac orci. Proin tincidunt eros eget risus laoreet, sit amet aliquam sem ornare. Integer ut eleifend lacus. Praesent at tempor sem. Nunc vel maximus nibh. Donec at bibendum massa. Praesent ullamcorper a odio vitae dignissim. Aenean id consectetur lacus. Fusce eu iaculis ex.";
	if(d=='slika7')document.getElementById("p1").innerHTML = "Cras vitae orci at odio consequat feugiat mattis ac quam. Donec libero ex, hendrerit non fringilla aliquam, elementum eu metus. In imperdiet congue dui sed tristique. Nam id lacus nisi. Duis tempor maximus risus sit amet luctus. Cras fringilla gravida ante non efficitur. In lectus felis, porta sit amet lorem nec, tincidunt lacinia erat. Suspendisse mollis sed sem et ultrices. Sed vel facilisis felis, quis faucibus massa. Pellentesque scelerisque urna ut ex mattis, at hendrerit dui accumsan. Nam nec vestibulum nunc. Etiam elementum semper diam rhoncus laoreet. Morbi vulputate dui at vulputate pellentesque. Aenean tempus pretium augue, at blandit quam semper id. Praesent auctor justo sit amet pellentesque tincidunt.";
}